from _root_path import add_root
add_root()

import numpy as np
import matplotlib.pyplot as plt

from skspatial.objects import Point, Points, Plane, LineSegment
from skspatial.transformation import transform_coordinates
from skspatial.plotting import plot_3d

from dataclasses import dataclass

import map_muscles.muscle_template.projection_on_plane as pp

class Segment():
    def __init__(self, two_points):
        self.A = Point(two_points[0])
        self.B = Point(two_points[1])

    def plotter(self, **kwargs):
        """
        Plotter method for the muscle template.
        It has to be unpacked in plot_3d() to be used: 
        
        e.g.:
        plot_3d(*Segment.plane_projection())

        Args:
            **kwargs: Additional keyword arguments to be passed to the underlying plotter methods.

        Returns:
            tuple: A tuple containing the plots generated by the underlying plotter methods for muscle A and muscle B.
        """
        plotter_A = self.A.plotter(**kwargs)
        plotter_B = self.B.plotter(**kwargs)

        return plotter_A, plotter_B
    
    def project_on_plane(self, plane: Plane):
        projected_A = plane.project_point(self.A)
        projected_B = plane.project_point(self.B)
        return Segment([projected_A, projected_B])
    
    def plot_segment(self, ax, **kwargs):
        ax.plot([self.A[0], self.B[0]], [self.A[1], self.B[1]], [self.A[2], self.B[2]], **kwargs)

# class Fiber = Segment
class Fiber(Segment):
    pass

def get_segments_plotters(segments, flatten=True, **kwargs):
    """
    Returns a list of plotters for each segment.

    Args:
        segments (list): A list of Segment objects.
        **kwargs: Additional keyword arguments to be passed to the segment plotter.

    Returns:
        list: A list of plotters for each segment.
    """
    plotters = np.array([segment.plotter(**kwargs) for segment in segments])

    if flatten:
        return plotters.flatten()
    return plotters

def get_segments_min_x(segments):
    return min([min(segment.A[0], segment.B[0]) for segment in segments])

def get_segments_max_x(segments):
    return max([max(segment.A[0], segment.B[0]) for segment in segments])

def get_segments_min_y(segments):
    return min([min(segment.A[1], segment.B[1]) for segment in segments])

def get_segments_max_y(segments):
    return max([max(segment.A[1], segment.B[1]) for segment in segments])

def get_segments_min_z(segments):
    return min([min(segment.A[2], segment.B[2]) for segment in segments])

def get_segments_max_z(segments):
    return max([max(segment.A[2], segment.B[2]) for segment in segments])

def get_segments_lims_x(segments):
    return [get_segments_min_x(segments), get_segments_max_x(segments)]

def get_segments_lims_y(segments):
    return [get_segments_min_y(segments), get_segments_max_y(segments)]

def get_segments_lims_z(segments):
    return [get_segments_min_z(segments), get_segments_max_z(segments)]

class Segments():
    segments: list # of Segment

    def __init__(self, segments):
        """
        Args:
            fibers (list): A list of Fiber (Segment).
        """
        self.segments = segments

    @classmethod
    def segments_from_points(cls, segments):
        """_summary_

        Args:
            segments (list): A list of two points tuple
        """
        return cls([Segment(segment) for segment in segments])

    def points_plotters(self, **kwargs):
        """
        Returns a list of plotters for each fiber.

        Args:
            **kwargs: Additional keyword arguments to be passed to the fiber plotter.

        Returns:
            list: A list of plotters for each fiber.
        """
        return get_segments_plotters(self.fibers, **kwargs)

    def plot_segments(self, ax, **kwargs):
        for segment in self.segments:
            segment.plot_segment(ax, **kwargs)

    def project_on_plane(self, plane: Plane):

        segments = [segment.project_on_plane(plane) for segment in self.segments]
        
        return Segments(segments)

    def get_min_x(self):
        return get_segments_min_x(self.segments)
    
    def get_max_x(self):
        return get_segments_max_x(self.segments)
    
    def get_min_y(self):
        return get_segments_min_y(self.segments)
    
    def get_max_y(self):
        return get_segments_max_y(self.segments)    
    def get_min_z(self):
        return get_segments_min_z(self.segments)
    
    def get_max_z(self):
        return get_segments_max_z(self.segments)
    
    def get_lims_x(self):
        return get_segments_lims_x(self.segments)
    
    def get_lims_y(self):
        return get_segments_lims_y(self.segments)
    
    def get_lims_z(self):
        return get_segments_lims_z(self.segments)
        
    def get_lims(self):
        return self.get_lims_x(), self.get_lims_y(), self.get_lims_z()
    

class Fibers(Segments):
    pass

class Muscles():
    muscles: list # of Fibers

    def __init__(self, muscles):
        """
        Args:
            muscles (list): A list of Fibers
        """
        self.muscles = muscles

    @classmethod
    def muscles_from_df(cls, muscles_df, line_key='line'):
        return cls([Fibers.fibers_from_points(muscle['line'].to_numpy()) for muscle in muscles_df])

#TODO



class SegmentedFiber(Fibers):
    segments: list # of Segment

    def __init__(self, segments):
        """
        Args:
            segments (list): A list of Segment
        """
        self.segments = segments

    def points_plotters(self, **kwargs):
        """
        Returns a list of plotters for each segment.

        Args:
            **kwargs: Additional keyword arguments to be passed to the segment plotter.

        Returns:
            list: A list of plotters for each segment.
        """
        return get_segments_plotters(self.segments, **kwargs)

    def plot_segments(self, ax, **kwargs):
        for segment in self.segments:
            segment.plot_segment(ax, **kwargs)
    
    def project_on_plane(self, plane: Plane):
        segments = [segment.project_on_plane(plane) for segment in self.segments]
        return SegmentedFiber(segments)
    
    def get_min_x(self):
        return get_segments_min_x(self.segments)
    
    def get_max_x(self):
        return get_segments_max_x(self.segments)
    
    def get_min_y(self):
        return get_segments_min_y(self.segments)
    
    def get_max_y(self):
        return get_segments_max_y(self.segments)
    
        
    
def one_muscle_to_fibers(muscle, line_key='line'):
    """
    Convert a muscle df to a Fibers object.

    Parameters:
    muscle (dict): A dictionary representing a muscle.
    line_key (str, optional): The key in the muscle dictionary that contains the fiber data. Defaults to 'line'.

    Returns:
    Fibers: A Fibers object representing the muscle's fibers.
    """
    return Fibers.segments_from_points(muscle[line_key].to_numpy())

def muscles_to_fibers(muscles, line_key='line'):
    """
    Convert a list of muscles dfs to a list of Fibers.

    Parameters:
    muscles (list): A list of dictionaries representing muscles.
    line_key (str, optional): The key in each muscle dictionary that contains the fiber data. Defaults to 'line'.

    Returns:
    list: A list of Fibers objects, each representing a muscle's fibers.
    """
    return [Fibers.segments_from_points(muscle[line_key].to_numpy()) for muscle in muscles]


if __name__ == "__main__":

    v1 = np.array([1.0,.0,.0])
    v2 = np.array([.0,1.0,.0])

    u1,u2 = pp.orthonormal_vectors(v1, v2)

    points = Points([[0, 0, 0], v1, v2])

    plane = Plane.from_points(points[0], points[1], points[2])
    segment = Segment([[0, 0, 1], [1, 1, 3]])

    projected_segment = segment.project_on_plane(plane)

    fig, ax = plot_3d(
        plane.plotter(alpha=0.2),
        *segment.plotter(c='k'),
        *projected_segment.plotter(c='r'),
    )

    segment.plot_segment(ax, c='k')
    projected_segment.plot_segment(ax, c='r')

    plt.show()